//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace ConferenceApp.Core.DataModels
{
	/// <summary>
	/// Database       : conference_db
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 11.5
	/// </summary>
	public partial class MainDb : LinqToDB.Data.DataConnection
	{
		public ITable<Collaborator> Collaborators { get { return this.GetTable<Collaborator>(); } }
		public ITable<Report>       Reports       { get { return this.GetTable<Report>(); } }
		public ITable<Request>      Requests      { get { return this.GetTable<Request>(); } }
		public ITable<User>         Users         { get { return this.GetTable<User>(); } }

		partial void InitMappingSchema()
		{
		}

		public MainDb()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MainDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="cf", Name="collaborators")]
	public partial class Collaborator
	{
		[Column("user_id"),   NotNull] public Guid UserId   { get; set; } // uuid
		[Column("report_id"), NotNull] public Guid ReportId { get; set; } // uuid

		#region Associations

		/// <summary>
		/// collaborators_report_id_fkey
		/// </summary>
		[Association(ThisKey="ReportId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="collaborators_report_id_fkey", BackReferenceName="Collaboratorsreportidfkeys")]
		public Report Report { get; set; }

		/// <summary>
		/// collaborators_user_id_fkey
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="collaborators_user_id_fkey", BackReferenceName="Collaboratorsuseridfkeys")]
		public User User { get; set; }

		#endregion
	}

	[Table(Schema="cf", Name="reports")]
	public partial class Report
	{
		[Column("id"),          PrimaryKey, NotNull] public Guid         Id         { get; set; } // uuid
		[Column("title"),                   NotNull] public string       Title      { get; set; } // character varying
		[Column("request_id"),              NotNull] public Guid         RequestId  { get; set; } // uuid
		[Column("report_type"),             NotNull] public ReportType   ReportType { get; set; } // integer
		[Column("file_name"),               NotNull] public string       FileName   { get; set; } // character varying
		[Column("path"),                    NotNull] public string       Path       { get; set; } // character varying
		[Column("status"),                  NotNull] public ReportStatus Status     { get; set; } // integer

		#region Associations

		/// <summary>
		/// collaborators_report_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ReportId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Collaborator> Collaboratorsreportidfkeys { get; set; }

		/// <summary>
		/// reports_request_id_fkey
		/// </summary>
		[Association(ThisKey="RequestId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="reports_request_id_fkey", BackReferenceName="Reportsrequestidfkeys")]
		public Request Request { get; set; }

		#endregion
	}

	[Table(Schema="cf", Name="requests")]
	public partial class Request
	{
		[Column("id"),       PrimaryKey, NotNull] public Guid          Id      { get; set; } // uuid
		[Column("owner_id"),             NotNull] public Guid          OwnerId { get; set; } // uuid
		[Column("status"),               NotNull] public RequestStatus Status  { get; set; } // integer

		#region Associations

		/// <summary>
		/// requests_owner_id_fkey
		/// </summary>
		[Association(ThisKey="OwnerId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="requests_owner_id_fkey", BackReferenceName="Requestsowneridfkeys")]
		public User Owner { get; set; }

		/// <summary>
		/// reports_request_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Report> Reportsrequestidfkeys { get; set; }

		#endregion
	}

	[Table(Schema="cf", Name="users")]
	public partial class User
	{
		[Column("id"),           PrimaryKey,  NotNull] public Guid   Id           { get; set; } // uuid
		[Column("first_name"),                NotNull] public string FirstName    { get; set; } // character varying
		[Column("middle_name"),     Nullable         ] public string MiddleName   { get; set; } // character varying
		[Column("last_name"),                 NotNull] public string LastName     { get; set; } // character varying
		[Column("degree"),                    NotNull] public Degree Degree       { get; set; } // integer
		[Column("organization"),              NotNull] public string Organization { get; set; } // character varying
		[Column("address"),                   NotNull] public string Address      { get; set; } // character varying
		[Column("phone"),                     NotNull] public string Phone        { get; set; } // character varying
		[Column("fax"),             Nullable         ] public string Fax          { get; set; } // character varying
		[Column("email"),                     NotNull] public string Email        { get; set; } // character varying

		#region Associations

		/// <summary>
		/// collaborators_user_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Collaborator> Collaboratorsuseridfkeys { get; set; }

		/// <summary>
		/// requests_owner_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="OwnerId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Request> Requestsowneridfkeys { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Report Find(this ITable<Report> table, Guid Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Request Find(this ITable<Request> table, Guid Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static User Find(this ITable<User> table, Guid Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
